#!/bin/sh

prf() { printf %s\\n "$*" ; }

# Import all needed variables and functions from plugins
source $PWD/config
source $PWD/plugins/get_time
source $PWD/plugins/get_battery

init

# Align when script checks for the current time to be accurate
upbar
sleep "$(goffset)"

# Adjusts for computation time
synct

while true; do
	for i in $(seq 0 4); do
		min1
		upbar
		sleep "$ms"
	done
	min5
done
